### ISSUE TITLE
Consider using http.DetectContentType to inter the image type

### ISSUE THREAD

**Issue by h2non** [DAddYE/vips#13]
Probably this algorithm will be more reliable than checking the first chunk of bytes of the image:
http://golang.org/src/net/http/sniff.go?s=648:690#L11

**Comment by lovell** [comment]
> "more reliable than checking the first chunk of bytes"

If you're happy with the minimum version of libvips being 7.40.0+, I recommend using `vips_foreign_find_load_buffer` for this purpose as it performs some basic verification of image metadata also - see https://github.com/lovell/sharp/blob/judgement/src/common.cc#L40

**Comment by h2non** [comment]
That's a good idea and probably better than Go `net/http` implementation just because it only checks image types. I'll support it. The restriction with  `libvips` minimum required version is not a big deal

**Comment by lovell** [comment]
Great, thanks Tomás.

`vips_foreign_find_load_buffer` has the added advantage of providing a run-time check of formats available at compile time. For example, if libvips is compiled without WebP support and is therefore unable to decode that format then this method won't detect it.

**Comment by h2non** [comment]
That's absolutely fantastic. In fact, I experimented some troubles yesterday with that because my original `libvips` compilation has no support for `webp`, so I was getting a `nil` pointer dereference runtime panic, which is very ugly. Using that function I can  handle that cases better with a graceful error

**Comment by h2non** [comment]
@lovell I've finally used supported your proposal: 
https://github.com/h2non/bimg/blob/master/vips.go#L172

Thanks!
