### ISSUE TITLE
Width of returned image is off by one

### ISSUE THREAD

**Issue by foresmac** [DAddYE/vips#16]
We replaced http://github.com/disintegration/imaging with vips in an image proxy to speed up resize operations. They are faster, but in our test suite I keep getting errors where the returned image width is 1 pixel greater than the specified width. I suspect (but have not been able to verify) that the difference is due to our calculations for height. Since I always want proportional scaling, can I just include the width and let vips figure out the height? I can't seem to find the documentation I'm looking for to figure this out on my own.

**Comment by foresmac** [comment]
```
----------------------------------------------------------------------
FAIL: resize_test.go:182: ResizeSuite.TestResizeColdCache

resize_test.go:201:
    c.Assert(img.Bounds().Size().X, Equals, width)
... obtained int = 430
... expected int = 431

----------------------------------------------------------------------
FAIL: resize_test.go:84: ResizeSuite.TestResizeImage

resize_test.go:106:
    c.Assert(image.Bounds().Size().X, Equals, width)
... obtained int = 430
... expected int = 431

----------------------------------------------------------------------
FAIL: resize_test.go:111: ResizeSuite.TestResizeNoExifImage

resize_test.go:126:
    c.Assert(image.Bounds().Size().X, Equals, width)
... obtained int = 682
... expected int = 683
```

**Comment by DAddYE** [comment]
Hi @foresmac can you provide me (or feel free to submit a pr) the tests?

**Comment by DAddYE** [comment]
Also @foresmac can you tell me how much faster and how much reduction in memory usage?

Thanks a lot!

**Comment by foresmac** [comment]
Here's a comparison using `imaging` vs `vips`:
```
PASS: resize_test.go:67: ResizeSuite.BenchmarkLargeResize         10     154245076 ns/op
PASS: resize_test.go:51: ResizeSuite.BenchmarkThumbnailResize         20      73262111 ns/op

PASS: resize_test.go:68: ResizeSuite.BenchmarkLargeResize         50      45374850 ns/op
PASS: resize_test.go:52: ResizeSuite.BenchmarkThumbnailResize         50      30855967 ns/op
```

so, like, 2–3x faster?

**Comment by foresmac** [comment]
Here's where I think the problem is:

```go
factor := float64(c.Width) / float64(img.Bounds().Size().X)
height := int(float64(img.Bounds().Size().Y) * factor)
```
`c.Width` is an `int` specifying the expected pixel width of the resultant image, while `height` is calculated from it. Then we're doing:

```go
options := vips.Options{
		Width:        c.Width,
		Height:       height,
		Crop:         false,
		Extend:       vips.EXTEND_WHITE,
		Interpolator: vips.BILINEAR,
		Gravity:      vips.CENTRE,
		Quality:      80,
	}

	res, err := vips.Resize(raw, options)
```

If I add one to the height calculation, different test cases (there are multiple) fail.

Here are the cases; I set the width and then check that the height matches, but it's failing before it ever checks the height.

```go
sizes = map[int]int{
		250:  333,
		500:  666,
		160:  213,
		720:  960,
		1024: 1365,
		683:  910,
		431:  574,
	}
```

The original image size is `2448 × 3264`.

**Comment by foresmac** [comment]
Maybe I should be using rounding? So, for instance, if the width is supposed to be 500, I calculate 666 for height but that's truncated from 666.6666....

**Comment by DAddYE** [comment]
cc @lovell

**Comment by foresmac** [comment]
I guess the question is, _must_ I supply a height option, or would vips just do the right thing?

**Comment by DAddYE** [comment]
It should do the right thing.

Specifically we round with [math.Floor](http://golang.org/pkg/math/#Floor)  [here](https://github.com/DAddYE/vips/blob/master/vips.go#L138)

**Comment by foresmac** [comment]
Cool, I'll try that. Thanks.

**Comment by DAddYE** [comment]
Keep me updated, if you want to give a shot I wrote also this: https://github.com/daddye/trez

**Comment by foresmac** [comment]
Yeah, I deleted all the calc code and now my widths are find but heights are a little off. I'll have to recalc my test cases, but I think the added benefit here is that I can also skip loading the data into an `image.Image` to figure out the pixel dimensions to do those calculations.

**Comment by foresmac** [comment]
Well, I tried recalculating the resultant heights, and some are still coming out 1 pixel off. I'd just change the test, but it means images might not fit when a client pre-calculates the expected image size and generates a view (i.e. in an iOS view controller).

**Comment by DAddYE** [comment]
Okay, I'll fix that.

**Comment by foresmac** [comment]
I'm not really sure where the problem is, though.

Here's my pre-calculated expected heights using the same formula you pointed to earlier, but for instance, I get `911` back instead of `910` for a width of `683`.

``` python
>>> orig_w = 2448
>>> orig_h = 3264
>>> widths = [250, 500, 160, 720, 1024, 683, 431]
>>> import math
>>> for width in widths:
...     factor = float(orig_w) / width
...     height = int(math.floor(orig_h / factor))
...     print "{0}: {1},".format(width, height)
... 
250: 333,
500: 666,
160: 213,
720: 960,
1024: 1365,
683: 910,
431: 574,
>>>
```

**Comment by foresmac** [comment]
```
FAIL: resize_test.go:182: ResizeSuite.TestResizeColdCache

resize_test.go:202:
    c.Assert(img.Bounds().Size().Y, Equals, height)
... obtained int = 911
... expected int = 910
```

**Comment by lovell** [comment]
Hi Chris, are you able to try using `Crop: true`. This is default behaviour in the upstream sharp module and irons out any rounding errors introduced along the way. (A resize operation consists of 1 or 2 integer shrinks plus a float affine reduction, if required).

**Comment by foresmac** [comment]
@lovell If I use `Crop: true`, then I also need to supply the height, correct?

**Comment by foresmac** [comment]
@lovell That worked, thanks!

Now I just need to better understand how to use crop in the future to generate square thumbnails.

**Comment by lovell** [comment]
@foresmac https://github.com/DAddYE/vips/blob/master/vips.go#L124-L148 can handle 0, 1 or 2 dimensions so width-only should be fine.

**Comment by lovell** [comment]
@DAddYE Should we make `Crop: true` the default behaviour?

**Comment by DAddYE** [comment]
@lovell yes

**Comment by foresmac** [comment]
@DAddYE @lovell I think I understand now; the code is specifically written to basically "do the right thing" given a fixed width and height. The good news is I think I can just replace our existing code for square crops with the right call to `vips.Resize()`. Thanks again for all your help in sorting this out.
