### ISSUE TITLE
Black background after PNG resize with alpha channel

### ISSUE THREAD

**Issue by alehano** [DAddYE/vips#21]
Black background after PNG resize with alpha channel. How can I set it to white?

**Comment by jcupitt** [comment]
All libvips save operations have a `background` argument you can use to set the colour an alpha channel is flattened out with. For example:

```
$ vips copy a.png x.jpg[background=255]
$ vips copy a.png x.jpg[background="255 128 128"]
```

**Comment by alehano** [comment]
Is there an API in go code?

**Comment by foresmac** [comment]
@jcupitt Will libvips not maintain alpha channels?

**Comment by jcupitt** [comment]
@foresmac libvips keeps the alpha if you resize png -> png. 

This issue (I think?) is resizing png -> jpg. In this case, libvips defaults to a black background and if you need a different colour, you have to specify it.

**Comment by foresmac** [comment]
@jcupitt Ah, this is apparently the exact problem we were having. Thanks for the insight!

**Comment by foresmac** [comment]
Looks like vips is always using JPEG output: https://github.com/DAddYE/vips/blob/master/vips.go#L318

**Comment by DAddYE** [comment]
The reason is that png is petty slow and the aim of the library was to make resize fast.

**Comment by foresmac** [comment]
@DAddYE Understandable.

**Comment by DAddYE** [comment]
But yes, it's not hard to make it work with png too ;)

**Comment by bgentry** [comment]
I would also like to see support for keeping PNGs as PNGs :+1: 

Thanks for making this library!
