### ISSUE TITLE
Incompatible library version: libvips.42.dylib requires version 4601.0.0 or later, but libgmodule-2.0.0.dylib provides version 4401.0.0

### ISSUE THREAD

**Issue by JohnnieFucker** [DAddYE/vips#29]
I install libvips already succeed in my mac osx,but there's error like this when I check the version.

$ vips --version
dyld: Library not loaded: /usr/local/lib/libgmodule-2.0.0.dylib
  Referenced from: /usr/local/bin/vips
  Reason: Incompatible library version: vips requires version 4601.0.0 or later, but libgmodule-2.0.0.dylib provides version 4401.0.0

how can I upgrade the libgmodule,I google it but there's nothing help.

**Comment by lovell** [comment]
Looks like `glib` is out of date. If you installed via homebrew then perhaps try `brew update && brew upgrade glib`.

**Comment by JohnnieFucker** [comment]
thanks ,that's the way!
