### ISSUE TITLE
Thumbnail

### ISSUE THREAD

**Issue by matrixik** [DAddYE/vips#3]
Hi,

Any plans to merge `feature/thumbnail` branch?

Best regards

**Comment by DAddYE** [comment]
It's planned to be merged once I'll figure out two things:

1. Trimming an image
2. Multithread with jpeg

Especially point 2 is important to me recent releases of libjpeg are finally thread safe (unless two threads modify the same image) and at the time I wrote/ported the script libvips was locking

**Comment by matrixik** [comment]
Thank you for reply.
