### ISSUE TITLE
Downsizing to fill specific sizes

### ISSUE THREAD

**Issue by matrixik** [DAddYE/vips#4]
Hi,

Is it possible with existing code to downscale image with preserving its aspect ratio to fill specific sizes?
Something like https://github.com/nfnt/resize/blob/master/thumbnail.go#L23 

Or should I use something similar like this function in my code or maybe I'm missing something?

Best Regards

**Comment by DAddYE** [comment]
Merged #5 can you double check if now is working for you as you expect?

**Comment by matrixik** [comment]
Hi,

Thank you for this patch!

It's passing all my tests except one:
```
func TestResize(t *testing.T) {
	var testCases = []struct {
		origWidth      int
		origHeight     int
		maxWidth       int
		maxHeight      int
		expectedWidth  uint
		expectedHeight uint
	}{
		{5, 5, 10, 10, 5, 5},
		{10, 10, 5, 5, 5, 5},
		{10, 50, 10, 10, 2, 10},
		{50, 10, 10, 10, 10, 2},
		{50, 100, 60, 90, 45, 90},
		{120, 100, 60, 90, 60, 50},
		{200, 250, 200, 150, 120, 150},
	}

	for index, mt := range testCases {
		img := image.NewGray16(image.Rect(0, 0, mt.origWidth, mt.origHeight))
		buf := new(bytes.Buffer)
		err := jpeg.Encode(buf, img, nil)
		if err != nil {
			t.Errorf(
				"%d. jpeg.Encode(buf, img, nil) error: %#v",
				index, err)
		}

		options := vips.Options{
			Width:         mt.maxWidth,
			Height:        mt.maxHeight,
			Crop:          false,
			Enlarge:       false,
			Extend:        vips.EXTEND_WHITE,
			PreserveRatio: true,
			Interpolator:  vips.NOHALO,
			Gravity:       vips.CENTRE,
			Quality:       90,
		}
		newImg, err := vips.Resize(buf.Bytes(), options)
		if err != nil {
			t.Errorf(
				"%d. vips.Resize(imgData, %#v) error: %#v",
				index, options, err)
		}

		outImg, err := jpeg.Decode(bytes.NewReader(newImg))
		if err != nil {
			t.Errorf(
				"%d. jpeg.Decode(newImg) error: %#v",
				index, err)
		}

		newWidth := uint(outImg.Bounds().Dx())
		newHeight := uint(outImg.Bounds().Dy())
		if newWidth != mt.expectedWidth ||
			newHeight != mt.expectedHeight {
			t.Errorf("%d. ips.Resize(imgData, %#v) => "+
				"width: %v, height: %v, want width: %v, height: %v",
				index, options,
				newWidth, newHeight, mt.expectedWidth, mt.expectedHeight,
			)
		}
	}
}
```

Error:
```
=== RUN TestResize

(govips:10728): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(govips:10728): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(govips:10728): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(govips:10728): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(govips:10728): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
--- FAIL: TestResize (0.05s)
	helpers_test.go:221: 4. ips.Resize(imgData, vips.Options{Height:90, Width:60, Crop:false, Enlarge:false, Extend:4, PreserveRatio:true, Interpolator:2, Gravity:0, Quality:90}) => width: 50, height: 100, want width: 45, height: 90
FAIL
exit status 1
```

**Comment by DAddYE** [comment]
I'm on that right now. How it comes that I don't see `(govips:10728): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed` ?

**Comment by DAddYE** [comment]
Hi thanks for your test, I added it to this project. If you have more feel free to submit a pr.

Anyway your issue should be fixed by now :dancer:

**Comment by matrixik** [comment]
Hi,

I'll test it when back home.
Looking on code slightly: will filling sizes work now by default?
If I find some more time I will add more tests (this repo begs for them :P ).

Regarding `(govips:10728):` I installed libvips from sources on Saturday as described in README, Linux Mint 17.1.

**Comment by DAddYE** [comment]
> Looking on code slightly: will filling sizes work now by default?

yep it should

> If I find some more time I will add more tests (this repo begs for them :P ).

I have yet to find a proper test suite especially to test difference in the image while embedding or filling

**Comment by lovell** [comment]
> "to test difference in the image"

I'm still investigating [possible solutions](https://github.com/lovell/sharp/issues/122) to this in sharp - the [simple logic](https://github.com/mgmtio/dhash-image/blob/master/index.js#L23-L31) of [dhash](https://github.com/maccman/dhash) is my favourite so far.

**Comment by DAddYE** [comment]
Thanks @lovell !!! I'll take an eye on it as well!
