### ISSUE TITLE
PNG - How to always output

### ISSUE THREAD

**Issue by franklinwise** [DAddYE/vips#8]
I'd like to resize and convert all images to PNG's. Is there a way to do that?

**Comment by franklinwise** [comment]
Mainly I want to preserve transparency on all images.  I've been digging through the code... looks like it's not implemented.

**Comment by shifr** [comment]
Hi, franklinwise
Resize func saves all images as JPEG with libvips core function "vips_jpegsave_buffer". You can see this at  line 296 in vips.go

I've solved this problem by adding into vips.h
```
int
vips_pngsave_custom(VipsImage *in, void **buf, size_t *len, int strip, int quality, int interlace)
{
    return vips_pngsave_buffer(in, buf, len, "interlace", interlace, NULL);
}
```

And into vips.go
```
	if typ == PNG {
		C.vips_pngsave_custom(colourspaced, &ptr, &length, 1, C.int(o.Quality), 0)
	} else {
		C.vips_jpegsave_custom(colourspaced, &ptr, &length, 1, C.int(o.Quality), 0)
	}

```

**Comment by franklinwise** [comment]
great thank you @shifr
